# Generated by Django 3.2.5 on 2021-07-18 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubric',
            old_name='description',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='rubric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
