# Generated by Django 3.2.5 on 2021-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0002_auto_20210718_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
