# Generated by Django 3.2.5 on 2021-07-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0004_auto_20210718_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='Big O time and space are analyzed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Explain an approach to testing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Final code was idiomatically correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Final code was syntactically correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Presented & understood a working algorithm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Solution was the best possible option',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Stepped through their solution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Total Score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Used correct terminology',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Used the time available effectively',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Verbalized their thought process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Was not overconfident (not listening to suggestions)',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Was not under-confident (unsure of known algorithm)',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rubric',
            name='Whiteboard was readable (penmanship and spacing)',
            field=models.IntegerField(default=0),
        ),
    ]
