# Generated by Django 3.2.5 on 2021-07-20 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0005_auto_20210718_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubric',
            old_name='name',
            new_name='challenge',
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='owner',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='rubric',
            old_name='Asked meaningful clarifying questions',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Big O time and space are analyzed',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Explain an approach to testing',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Final code was idiomatically correct',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Final code was syntactically correct',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Identified inputs and outputs \t\t',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Identified optimal data structure and/or algorithm',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Presented & understood a working algorithm',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Solution was the best possible option',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Stepped through their solution',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Total Score',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Used correct terminology',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Used the time available effectively',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Verbalized their thought process',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Visually illustrated the problem domain',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Was not overconfident (not listening to suggestions)',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Was not under-confident (unsure of known algorithm)',
        ),
        migrations.RemoveField(
            model_name='rubric',
            name='Whiteboard was readable (penmanship and spacing)',
        ),
        migrations.AddField(
            model_name='rubric',
            name='analyze_solution_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='best_solution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='big_o',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='clarify_question',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='communicate_effectively_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='idiomatically_correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='illustrate_problem',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='inputs_outputs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='interpret_question_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='optimal_structure',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='overconfident',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='proctor',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='solve_problem_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='syntactically_correct',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='terminology',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='testing',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='thought_process',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='time_end',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='time_start',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='underconfident',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='use_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='walkthrough_solution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='whiteboard',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rubric',
            name='working_algorithm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
