# Generated by Django 3.2.5 on 2021-07-21 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rubrics', '0006_auto_20210720_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='total',
        ),
        migrations.AlterField(
            model_name='rubric',
            name='proctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
