# Generated by Django 3.2.5 on 2021-07-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0007_auto_20210721_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='time_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
