# Generated by Django 3.2.5 on 2021-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrics', '0008_auto_20210721_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='analyze_solution_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='challenge',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='interpret_question_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='solve_problem_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
